name: add_to_app_flutter_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_wall_layout: ^2.1.1

  # mimundoupc:
  #   path: "./modules/mimundoupc"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.add_to_app_flutter_module
    iosBundleIdentifier: com.example.addToAppFlutterModule
